name: Fetch and Update GitHub Contribution

on:
  schedule:
    - cron: "*/2 * * * *"
  push:
    paths:
      - 'index.html'

jobs:
  fetch-contribution:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install cheerio node-fetch

      - name: Execute update-index.js
        run: node update-index.js


